version: 2

jobs:
  build:
    docker:
      - image: rustlang/rust:nightly

    environment:
      TZ: "/usr/share/zoneinfo/Asia/Shanghai"

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Build
          command: |
            rustc --version --verbose
            cargo --version --verbose
            cargo build --release
      - run:
          name: Test
          command: rustup run stable cargo test
      - store_artifacts:
          name: releasing artifacts
          path: target/release/msdb
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
workflows:
  version: 2
  build_workflow:
    jobs:
      - build