version: 2

jobs:
  coverage:
    machine: true
    steps:
      - checkout
      - run:
          name: Coverage with docker
          command: docker run -it --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin:latest-nightly cargo tarpaulin -v --coveralls XnPe7Iw6HBv74eekTqiK0Bmswdv8ejz0U
  build:
    docker:
      - image: rustlang/rust:nightly

    environment:
      TZ: "/usr/share/zoneinfo/Asia/Shanghai"

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Build
          command: |
            rustc --version --verbose
            cargo --version --verbose
            cargo build --release
      - run:
          name: Test
          command: cargo test
      - store_artifacts:
          name: releasing artifacts
          path: target/release/msdb
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
workflows:
  version: 2
  build_workflow:
    jobs:
      - build
      - coverages